#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("CouchbaseSample.Android.Resource", IsApplication=true)]

namespace CouchbaseSample.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Couchbase.Lite.Android.Resource.String.library_name = global::CouchbaseSample.Android.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int actionbar_background = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int drawer_background = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int highlighted_text_color = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int image_view_background = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int list_text_color_selector = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int main_background = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int primary_text_color = 2131034115;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int activity_horizontal_margin = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int activity_vertical_margin = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int navigation_drawer_width = 2131099650;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bg_card = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int drawer_shadow = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_camera = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_camera_light = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_drawer = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_launcher = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090009
			public const int action_new_list = 2131296265;
			
			// aapt resource value: 0x7f090007
			public const int @checked = 2131296263;
			
			// aapt resource value: 0x7f090002
			public const int container = 2131296258;
			
			// aapt resource value: 0x7f090008
			public const int create_task = 2131296264;
			
			// aapt resource value: 0x7f090001
			public const int drawer_layout = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int image = 2131296256;
			
			// aapt resource value: 0x7f090004
			public const int listView = 2131296260;
			
			// aapt resource value: 0x7f090003
			public const int navigation_drawer = 2131296259;
			
			// aapt resource value: 0x7f090006
			public const int text = 2131296262;
			
			// aapt resource value: 0x7f090005
			public const int title = 2131296261;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_image_view = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_share = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int fragment_list_drawer = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int fragment_main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int view_list_drawer = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int view_task = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int view_task_create = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int view_user = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int global = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int image_view = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int main = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int share = 2131230723;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040006
			public const int action_delete = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int action_login = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int action_new_list = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int action_share = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int app_id = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040008
			public const int hint_create_task = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int hint_new_list = 2130968583;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f04000a
			public const int navigation_drawer_close = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int navigation_drawer_open = 2130968585;
			
			// aapt resource value: 0x7f04000d
			public const int title_activity_image_view = 2130968589;
			
			// aapt resource value: 0x7f04000b
			public const int title_activity_share = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int title_dialog_new_list = 2130968588;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int AppActionBar = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int AppTheme = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int IndeterminateProgressBar = 2131165186;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
