#!/bin/sh
echo Starting sync_gateway with option "'$1'"...
current=`pwd`
echo "$current"
if [ "$1" == "--use-server" ]; then
	pid=`cat ~/Library/Application\ Support/Couchbase/couchbase-server.pid`
	running=`ps aux | grep "$pid" | grep -v grep`
	if [ "$running" == "" ]; then
		echo Starting Couchbase Server...
		#`cd "/Applications/Couchbase\ Server.app/Contents/Resources";./start-server.sh"` &
		/Applications/Couchbase\ Server.app/Contents/MacOS/Couchbase\ Server&
		sleep 15
	else
		echo Couchbase Server is currently running.
	fi
	cd "$current"
	Tools/sync_gateway -pretty -verbose=true src/Couchbase.Lite.Tests.Shared/Assets/GatewayConfigCouchbaseServer.json
else
	Tools/sync_gateway -pretty -verbose=true src/Couchbase.Lite.Tests.Shared/Assets/GatewayConfig.json
fi