//
// C4BlobStore_native.cs
//
// Copyright (c) 2024 Couchbase, Inc All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// --------------------------------------------------
// <auto-generated>
// This file was generated by generate_bindings.ps1
// </auto-generated>
// --------------------------------------------------

using System;
using System.Linq;
using System.Runtime.InteropServices;

using LiteCore.Util;

namespace LiteCore.Interop
{

    internal unsafe static partial class Native
    {
        public static bool c4blob_keyFromString(string? str, C4BlobKey* x)
        {
            using(var str_ = new C4String(str)) {
                return NativeRaw.c4blob_keyFromString(str_.AsFLSlice(), x);
            }
        }

        public static string? c4blob_keyToString(C4BlobKey key)
        {
            using(var retVal = NativeRaw.c4blob_keyToString(key)) {
                return ((FLSlice)retVal).CreateString();
            }
        }

        [DllImport(Constants.DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern C4BlobStore* c4db_getBlobStore(C4Database* db, C4Error* outError);

        [DllImport(Constants.DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern long c4blob_getSize(C4BlobStore* store, C4BlobKey key);

        public static byte[]? c4blob_getContents(C4BlobStore* store, C4BlobKey key, C4Error* outError)
        {
            using(var retVal = NativeRaw.c4blob_getContents(store, key, outError)) {
                return ((FLSlice)retVal).ToArrayFast();
            }
        }

        public static bool c4blob_create(C4BlobStore* store, byte[]? contents, C4BlobKey* expectedKey, C4BlobKey* outKey, C4Error* error)
        {
            fixed(byte *contents_ = contents) {
                return NativeRaw.c4blob_create(store, new FLSlice(contents_, contents == null ? 0 : (ulong)contents.Length), expectedKey, outKey, error);
            }
        }

        [DllImport(Constants.DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern C4ReadStream* c4blob_openReadStream(C4BlobStore* store, C4BlobKey key, C4Error* outError);

        [DllImport(Constants.DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern UIntPtr c4stream_read(C4ReadStream* stream, [Out]byte[] buffer, UIntPtr maxBytesToRead, C4Error* outError);

        [DllImport(Constants.DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern long c4stream_getLength(C4ReadStream* stream, C4Error* outError);

        [DllImport(Constants.DllName, CallingConvention = CallingConvention.Cdecl)]
        [return: MarshalAs(UnmanagedType.U1)]
        public static extern bool c4stream_seek(C4ReadStream* stream, ulong position, C4Error* outError);

        [DllImport(Constants.DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern C4WriteStream* c4blob_openWriteStream(C4BlobStore* store, C4Error* outError);

        [DllImport(Constants.DllName, CallingConvention = CallingConvention.Cdecl)]
        [return:MarshalAs(UnmanagedType.U1)]
        public static extern bool c4stream_write(C4WriteStream* stream, byte[] bytes, UIntPtr length, C4Error* outError);

        [DllImport(Constants.DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern C4BlobKey c4stream_computeBlobKey(C4WriteStream* stream);

        [DllImport(Constants.DllName, CallingConvention = CallingConvention.Cdecl)]
        [return: MarshalAs(UnmanagedType.U1)]
        public static extern bool c4stream_install(C4WriteStream* stream, C4BlobKey* expectedKey, C4Error* outError);


    }

    internal unsafe static partial class NativeRaw
    {
        [DllImport(Constants.DllName, CallingConvention = CallingConvention.Cdecl)]
        [return: MarshalAs(UnmanagedType.U1)]
        public static extern bool c4blob_keyFromString(FLSlice str, C4BlobKey* x);

        [DllImport(Constants.DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern FLSliceResult c4blob_keyToString(C4BlobKey key);

        [DllImport(Constants.DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern FLSliceResult c4blob_getContents(C4BlobStore* store, C4BlobKey key, C4Error* outError);

        [DllImport(Constants.DllName, CallingConvention = CallingConvention.Cdecl)]
        [return: MarshalAs(UnmanagedType.U1)]
        public static extern bool c4blob_create(C4BlobStore* store, FLSlice contents, C4BlobKey* expectedKey, C4BlobKey* outKey, C4Error* error);


    }
}
