//
// C4IndexTypes_defs.cs
//
// Copyright (c) 2024 Couchbase, Inc All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// --------------------------------------------------
// <auto-generated>
// This file was generated by generate_bindings.ps1
// </auto-generated>
// --------------------------------------------------

#nullable enable
#pragma warning disable IDE0051 // Remove unused private members
#pragma warning disable IDE0044 // Add readonly modifier
#pragma warning disable CS0649  // Member never assigned to
#pragma warning disable CS0169  // Member never used


using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Threading;

using LiteCore.Util;

namespace LiteCore.Interop
{
    internal enum C4IndexType : uint
    {
        ValueIndex,
        FullTextIndex,
        ArrayIndex,
        PredictiveIndex,
        VectorIndex,
    }

    internal enum C4VectorMetricType : uint
    {
        VectorMetricDefault,
        VectorMetricEuclidean2,
        VectorMetricCosine,
        VectorMetricEuclidean1,
        VectorMetricDot,
    }

    internal enum C4VectorClusteringType : uint
    {
        VectorClusteringFlat,
        VectorClusteringMulti,
    }

    internal enum C4VectorEncodingType : uint
    {
        VectorEncodingDefault,
        VectorEncodingNone,
        VectorEncodingPQ,
        VectorEncodingSQ,
    }

	internal unsafe struct C4VectorClustering
    {
        public C4VectorClusteringType type;
        public uint flat_centroids;
        public uint multi_subquantizers;
        public uint multi_bits;
    }

	internal unsafe struct C4VectorEncoding
    {
        public C4VectorEncodingType type;
        public uint pq_subquantizers;
        public uint bits;
    }

	internal unsafe struct C4VectorIndexOptions
    {
        public uint dimensions;
        public C4VectorMetricType metric;
        public C4VectorClustering clustering;
        public C4VectorEncoding encoding;
        public uint minTrainingSize;
        public uint maxTrainingSize;
        public uint numProbes;
        private byte _lazy;

        public bool lazy
        {
            get {
                return Convert.ToBoolean(_lazy);
            }
            set {
                _lazy = Convert.ToByte(value);
            }
        }
    }

	internal unsafe partial struct C4IndexOptions
    {
        private IntPtr _language;
        private byte _ignoreDiacritics;
        private byte _disableStemming;
        private IntPtr _stopWords;
        private IntPtr _unnestPath;
        public C4VectorIndexOptions vector;

        public string? language
        {
            get {
                return Marshal.PtrToStringAnsi(_language);
            }
            set {
                var old = Interlocked.Exchange(ref _language, Marshal.StringToHGlobalAnsi(value));
                Marshal.FreeHGlobal(old);
            }
        }

        public bool ignoreDiacritics
        {
            get {
                return Convert.ToBoolean(_ignoreDiacritics);
            }
            set {
                _ignoreDiacritics = Convert.ToByte(value);
            }
        }

        public bool disableStemming
        {
            get {
                return Convert.ToBoolean(_disableStemming);
            }
            set {
                _disableStemming = Convert.ToByte(value);
            }
        }

        public string? stopWords
        {
            get {
                return Marshal.PtrToStringAnsi(_stopWords);
            }
            set {
                var old = Interlocked.Exchange(ref _stopWords, Marshal.StringToHGlobalAnsi(value));
                Marshal.FreeHGlobal(old);
            }
        }

        public string? unnestPath
        {
            get {
                return Marshal.PtrToStringAnsi(_unnestPath);
            }
            set {
                var old = Interlocked.Exchange(ref _unnestPath, Marshal.StringToHGlobalAnsi(value));
                Marshal.FreeHGlobal(old);
            }
        }
    }
}

#pragma warning restore IDE0051 // Remove unused private members
#pragma warning restore IDE0044 // Add readonly modifier
#pragma warning restore CS0649  // Member never assigned to
#pragma warning restore CS0169  // Member never used
