//
// C4Observer_native.cs
//
// Copyright (c) 2025 Couchbase, Inc All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// --------------------------------------------------
// <auto-generated>
// This file was generated by generate_bindings.ps1
// </auto-generated>
// --------------------------------------------------

#nullable enable

using System;
using System.Linq;
using System.Runtime.InteropServices;

#if NET8_0_OR_GREATER
using System.Runtime.InteropServices.Marshalling;
#endif

using LiteCore.Util;

namespace LiteCore.Interop
{

    internal static unsafe partial class Native
    {
        [DllImport(Constants.DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern C4CollectionObserver* c4dbobs_createOnCollection(C4Collection* collection, C4CollectionObserverCallback callback, void* context, C4Error* error);

        [DllImport(Constants.DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern C4CollectionObservation c4dbobs_getChanges(C4CollectionObserver* observer, [Out]C4CollectionChange[] outChanges, uint maxChanges);

        [DllImport(Constants.DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void c4dbobs_releaseChanges(C4CollectionChange[] changes, uint numChanges);

#if NET8_0_OR_GREATER
        [LibraryImport(Constants.DllName, StringMarshallingCustomType = typeof(FLSliceMarshaller))]
        public static partial C4DocumentObserver* c4docobs_createWithCollection(C4Collection* collection, string? docID, C4DocumentObserverCallback callback, void* context, C4Error* error);
#else
        public static C4DocumentObserver* c4docobs_createWithCollection(C4Collection* collection, string? docID, C4DocumentObserverCallback callback, void* context, C4Error* error)
        {
            using var docID_ = new C4String(docID); {
                return NativeRaw.c4docobs_createWithCollection(collection, docID_.AsFLSlice(), callback, context, error);
            }
        }
#endif

        [DllImport(Constants.DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern C4QueryObserver* c4queryobs_create(C4Query* query, C4QueryObserverCallback callback, void* context);

        [DllImport(Constants.DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void c4queryobs_setEnabled(C4QueryObserver* obs, [MarshalAs(UnmanagedType.U1)]bool enabled);

        [DllImport(Constants.DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern C4QueryEnumerator* c4queryobs_getEnumerator(C4QueryObserver* obs, [MarshalAs(UnmanagedType.U1)]bool forget, C4Error* error);


    }

    internal static unsafe partial class NativeRaw
    {
        [DllImport(Constants.DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern C4DocumentObserver* c4docobs_createWithCollection(C4Collection* collection, FLSlice docID, C4DocumentObserverCallback callback, void* context, C4Error* error);


    }
}
