//
// C4Socket_native.cs
//
// Copyright (c) 2025 Couchbase, Inc All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// --------------------------------------------------
// <auto-generated>
// This file was generated by generate_bindings.ps1
// </auto-generated>
// --------------------------------------------------

#nullable enable

using System;
using System.Linq;
using System.Runtime.InteropServices;

#if NET8_0_OR_GREATER
using System.Runtime.InteropServices.Marshalling;
#endif

using LiteCore.Util;

namespace LiteCore.Interop
{

    internal static unsafe partial class Native
    {
        [DllImport(Constants.DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void c4socket_registerFactory(C4SocketFactory factory);

        [DllImport(Constants.DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void c4Socket_setNativeHandle(C4Socket* socket, void* x);

        [DllImport(Constants.DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void* c4Socket_getNativeHandle(C4Socket* socket);

        [DllImport(Constants.DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void c4socket_gotHTTPResponse(C4Socket* socket, int httpStatus, FLSlice responseHeadersFleece);

        [DllImport(Constants.DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void c4socket_opened(C4Socket* socket);

        [DllImport(Constants.DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void c4socket_closed(C4Socket* socket, C4Error errorIfAny);

#if NET8_0_OR_GREATER
        [LibraryImport(Constants.DllName, StringMarshallingCustomType = typeof(FLSliceMarshaller))]
        public static partial void c4socket_closeRequested(C4Socket* socket, int status, string? message);
#else
        public static void c4socket_closeRequested(C4Socket* socket, int status, string? message)
        {
            using var message_ = new C4String(message); {
                NativeRaw.c4socket_closeRequested(socket, status, message_.AsFLSlice());
            }
        }
#endif

#if NET8_0_OR_GREATER
        [LibraryImport(Constants.DllName)]
        public static partial void c4socket_completedWrite(C4Socket* socket, ulong byteCount);
#else
        public static void c4socket_completedWrite(C4Socket* socket, ulong byteCount)
        {
            NativeRaw.c4socket_completedWrite(socket, (UIntPtr)byteCount);
        }
#endif

#if NET8_0_OR_GREATER
        [LibraryImport(Constants.DllName)]
        public static partial void c4socket_received(C4Socket* socket, [MarshalUsing(typeof(FLSliceMarshaller))] byte[]? data);
#else
        public static void c4socket_received(C4Socket* socket, byte[]? data)
        {
            fixed(byte *data_ = data) {
                NativeRaw.c4socket_received(socket, new FLSlice(data_, data == null ? 0 : (ulong)data.Length));
            }
        }
#endif

        [DllImport(Constants.DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern C4Socket* c4socket_fromNative(C4SocketFactory factory, void* nativeHandle, C4Address* address);


    }

    internal static unsafe partial class NativeRaw
    {
        [DllImport(Constants.DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void c4socket_closeRequested(C4Socket* socket, int status, FLSlice message);

        [DllImport(Constants.DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void c4socket_completedWrite(C4Socket* socket, UIntPtr byteCount);

        [DllImport(Constants.DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void c4socket_received(C4Socket* socket, FLSlice data);


    }
}
