// 
//  ILiteCore.cs
// 
//  Copyright (c) 2019 Couchbase, Inc All rights reserved.
// 
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
// 
//  http://www.apache.org/licenses/LICENSE-2.0
// 
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
// 
using System;

namespace LiteCore.Interop
{
    internal sealed unsafe partial class LiteCoreImpl : ILiteCore
    {
        public long c4_now() => Native.c4_now();
        public string c4error_getMessage(C4Error error) => Native.c4error_getMessage(error);
        public C4Error c4error_make(C4ErrorDomain domain, int code, string message) => Native.c4error_make(domain, code, message);
        public bool c4error_mayBeTransient(C4Error err) => Native.c4error_mayBeTransient(err);
        public bool c4error_mayBeNetworkDependent(C4Error err) => Native.c4error_mayBeNetworkDependent(err);
        public void c4log_writeToCallback(C4LogLevel level, C4LogCallback callback, bool preformatted) => Native.c4log_writeToCallback(level, callback, preformatted);
        public bool c4log_writeToBinaryFile(C4LogFileOptions options, C4Error* error) => Native.c4log_writeToBinaryFile(options, error);
        public C4LogLevel c4log_callbackLevel() => Native.c4log_callbackLevel();
        public void c4log_setCallbackLevel(C4LogLevel level) => Native.c4log_setCallbackLevel(level);
        public C4LogLevel c4log_binaryFileLevel() => Native.c4log_binaryFileLevel();
        public void c4log_setBinaryFileLevel(C4LogLevel level) => Native.c4log_setBinaryFileLevel(level);
        public string c4log_getDomainName(C4LogDomain* x) => Native.c4log_getDomainName(x);
        public C4LogLevel c4log_getLevel(C4LogDomain* x) => Native.c4log_getLevel(x);
        public void c4log_setLevel(C4LogDomain* c4Domain, C4LogLevel level) => Native.c4log_setLevel(c4Domain, level);
        public void c4slog(C4LogDomain* domain, C4LogLevel level, string msg) => Native.c4slog(domain, level, msg);
        public string c4_getVersion() => Native.c4_getVersion();
        public int c4_getObjectCount() => Native.c4_getObjectCount();
        public bool c4blob_keyFromString(string str, C4BlobKey* x) => Native.c4blob_keyFromString(str, x);
        public string c4blob_keyToString(C4BlobKey key) => Native.c4blob_keyToString(key);
        public C4BlobStore* c4db_getBlobStore(C4Database* db, C4Error* outError) => Native.c4db_getBlobStore(db, outError);
        public C4BlobStore* c4blob_openStore(string dirPath, C4DatabaseFlags flags, C4EncryptionKey* encryptionKey, C4Error* outError) => Native.c4blob_openStore(dirPath, flags, encryptionKey, outError);
        public bool c4blob_deleteStore(C4BlobStore* store, C4Error* outError) => Native.c4blob_deleteStore(store, outError);
        public long c4blob_getSize(C4BlobStore* store, C4BlobKey key) => Native.c4blob_getSize(store, key);
        public byte[] c4blob_getContents(C4BlobStore* store, C4BlobKey key, C4Error* outError) => Native.c4blob_getContents(store, key, outError);
        public string c4blob_getFilePath(C4BlobStore* store, C4BlobKey key, C4Error* outError) => Native.c4blob_getFilePath(store, key, outError);
        public bool c4blob_create(C4BlobStore* store, byte[] contents, C4BlobKey* expectedKey, C4BlobKey* outKey, C4Error* error) => Native.c4blob_create(store, contents, expectedKey, outKey, error);
        public bool c4blob_delete(C4BlobStore* store, C4BlobKey key, C4Error* outError) => Native.c4blob_delete(store, key, outError);
        public C4ReadStream* c4blob_openReadStream(C4BlobStore* store, C4BlobKey key, C4Error* outError) => Native.c4blob_openReadStream(store, key, outError);
        public ulong c4stream_read(C4ReadStream *stream, byte[] buffer, int count, C4Error *outError) => Native.c4stream_read(stream, buffer, count, outError);
        public long c4stream_getLength(C4ReadStream* stream, C4Error* outError) => Native.c4stream_getLength(stream, outError);
        public bool c4stream_seek(C4ReadStream* stream, ulong position, C4Error* outError) => Native.c4stream_seek(stream, position, outError);
        public void c4stream_close(C4ReadStream* stream) => Native.c4stream_close(stream);
        public C4WriteStream* c4blob_openWriteStream(C4BlobStore* store, C4Error* outError) => Native.c4blob_openWriteStream(store, outError);
        public bool c4stream_write(C4WriteStream* stream, byte[] bytes, ulong length, C4Error* outError) => Native.c4stream_write(stream, bytes, length, outError);
        public C4BlobKey c4stream_computeBlobKey(C4WriteStream* stream) => Native.c4stream_computeBlobKey(stream);
        public bool c4stream_install(C4WriteStream* stream, C4BlobKey* expectedKey, C4Error* outError) => Native.c4stream_install(stream, expectedKey, outError);
        public void c4stream_closeWriter(C4WriteStream* stream) => Native.c4stream_closeWriter(stream);
        public C4Database* c4db_open(string path, C4DatabaseConfig* config, C4Error* outError) => Native.c4db_open(path, config, outError);
        public bool c4db_copy(string sourcePath, string destinationPath, C4DatabaseConfig* config, C4Error* error) => Native.c4db_copy(sourcePath, destinationPath, config, error);
        public C4Database* c4db_retain(C4Database* db) => Native.c4db_retain(db);
        public void c4db_free(C4Database* database) => Native.c4db_free(database);
        public bool c4db_close(C4Database* database, C4Error* outError) => Native.c4db_close(database, outError);
        public bool c4db_delete(C4Database* database, C4Error* outError) => Native.c4db_delete(database, outError);
        public bool c4db_deleteAtPath(string dbPath, C4Error* outError) => Native.c4db_deleteAtPath(dbPath, outError);
        public bool c4db_rekey(C4Database* database, C4EncryptionKey* newKey, C4Error* outError) => Native.c4db_rekey(database, newKey, outError);
        public bool c4_shutdown(C4Error* outError) => Native.c4_shutdown(outError);
        public string c4db_getPath(C4Database* db) => Native.c4db_getPath(db);
        public C4DatabaseConfig* c4db_getConfig(C4Database* db) => Native.c4db_getConfig(db);
        public ulong c4db_getDocumentCount(C4Database* database) => Native.c4db_getDocumentCount(database);
        public ulong c4db_getLastSequence(C4Database* database) => Native.c4db_getLastSequence(database);
        public long c4db_nextDocExpiration(C4Database* database) => Native.c4db_nextDocExpiration(database);
        public long c4db_purgeExpiredDocs(C4Database* db, C4Error* outError) => Native.c4db_purgeExpiredDocs(db, outError);
        public uint c4db_getMaxRevTreeDepth(C4Database* database) => Native.c4db_getMaxRevTreeDepth(database);
        public void c4db_setMaxRevTreeDepth(C4Database* database, uint maxRevTreeDepth) => Native.c4db_setMaxRevTreeDepth(database, maxRevTreeDepth);
        public bool c4db_getUUIDs(C4Database* database, C4UUID* publicUUID, C4UUID* privateUUID, C4Error* outError) => Native.c4db_getUUIDs(database, publicUUID, privateUUID, outError);
        public bool c4db_compact(C4Database* database, C4Error* outError) => Native.c4db_compact(database, outError);
        public bool c4db_beginTransaction(C4Database* database, C4Error* outError) => Native.c4db_beginTransaction(database, outError);
        public bool c4db_endTransaction(C4Database* database, bool commit, C4Error* outError) => Native.c4db_endTransaction(database, commit, outError);
        public bool c4db_isInTransaction(C4Database* database) => Native.c4db_isInTransaction(database);
        public void c4raw_free(C4RawDocument* rawDoc) => Native.c4raw_free(rawDoc);
        public C4RawDocument* c4raw_get(C4Database* database, string storeName, string docID, C4Error* outError) => Native.c4raw_get(database, storeName, docID, outError);
        public bool c4raw_put(C4Database* database, string storeName, string key, string meta, string body, C4Error* outError) => Native.c4raw_put(database, storeName, key, meta, body, outError);
        public void c4enum_close(C4DocEnumerator* e) => Native.c4enum_close(e);
        public void c4enum_free(C4DocEnumerator* e) => Native.c4enum_free(e);
        public C4DocEnumerator* c4db_enumerateChanges(C4Database* database, ulong since, C4EnumeratorOptions* options, C4Error* outError) => Native.c4db_enumerateChanges(database, since, options, outError);
        public C4DocEnumerator* c4db_enumerateAllDocs(C4Database* database, C4EnumeratorOptions* options, C4Error* outError) => Native.c4db_enumerateAllDocs(database, options, outError);
        public bool c4enum_next(C4DocEnumerator* e, C4Error* outError) => Native.c4enum_next(e, outError);
        public C4Document* c4enum_getDocument(C4DocEnumerator* e, C4Error* outError) => Native.c4enum_getDocument(e, outError);
        public bool c4enum_getDocumentInfo(C4DocEnumerator* e, C4DocumentInfo* outInfo) => Native.c4enum_getDocumentInfo(e, outInfo);
        public bool c4doc_isOldMetaProperty(string prop) => Native.c4doc_isOldMetaProperty(prop);
        public bool c4doc_dictContainsBlobs(FLDict* dict) => Native.c4doc_dictContainsBlobs(dict);
        public byte[] c4doc_getBlobData(FLDict* dict, C4BlobStore* blobStore, C4Error* outError) => Native.c4doc_getBlobData(dict, blobStore, outError);
        public FLEncoder* c4db_getSharedFleeceEncoder(C4Database* db) => Native.c4db_getSharedFleeceEncoder(db);
        public byte[] c4db_encodeJSON(C4Database* db, string jsonData, C4Error* outError) => Native.c4db_encodeJSON(db, jsonData, outError);
        public FLSharedKeys* c4db_getFLSharedKeys(C4Database* db) => Native.c4db_getFLSharedKeys(db);
        public C4Document* c4doc_get(C4Database* database, string docID, bool mustExist, C4Error* outError) => Native.c4doc_get(database, docID, mustExist, outError);
        public C4Document* c4doc_getBySequence(C4Database* database, ulong sequence, C4Error* outError) => Native.c4doc_getBySequence(database, sequence, outError);
        public bool c4doc_save(C4Document* doc, uint maxRevTreeDepth, C4Error* outError) => Native.c4doc_save(doc, maxRevTreeDepth, outError);
        public void c4doc_free(C4Document* doc) => Native.c4doc_free(doc);
        public bool c4doc_selectRevision(C4Document* doc, string revID, bool withBody, C4Error* outError) => Native.c4doc_selectRevision(doc, revID, withBody, outError);
        public bool c4doc_selectCurrentRevision(C4Document* doc) => Native.c4doc_selectCurrentRevision(doc);
        public bool c4doc_loadRevisionBody(C4Document* doc, C4Error* outError) => Native.c4doc_loadRevisionBody(doc, outError);
        public bool c4doc_hasRevisionBody(C4Document* doc) => Native.c4doc_hasRevisionBody(doc);
        public bool c4doc_selectParentRevision(C4Document* doc) => Native.c4doc_selectParentRevision(doc);
        public bool c4doc_selectNextRevision(C4Document* doc) => Native.c4doc_selectNextRevision(doc);
        public bool c4doc_selectNextLeafRevision(C4Document* doc, bool includeDeleted, bool withBody, C4Error* outError) => Native.c4doc_selectNextLeafRevision(doc, includeDeleted, withBody, outError);
        public bool c4doc_selectFirstPossibleAncestorOf(C4Document* doc, string revID) => Native.c4doc_selectFirstPossibleAncestorOf(doc, revID);
        public bool c4doc_selectNextPossibleAncestorOf(C4Document* doc, string revID) => Native.c4doc_selectNextPossibleAncestorOf(doc, revID);
        public bool c4doc_selectCommonAncestorRevision(C4Document* doc, string rev1ID, string rev2ID) => Native.c4doc_selectCommonAncestorRevision(doc, rev1ID, rev2ID);
        public uint c4rev_getGeneration(string revID) => Native.c4rev_getGeneration(revID);
        public int c4doc_purgeRevision(C4Document* doc, string revID, C4Error* outError) => Native.c4doc_purgeRevision(doc, revID, outError);
        public bool c4doc_resolveConflict(C4Document* doc, string winningRevID, string losingRevID, byte[] mergedBody, C4RevisionFlags mergedFlags, C4Error* error) => Native.c4doc_resolveConflict(doc, winningRevID, losingRevID, mergedBody, mergedFlags, error);
        public bool c4db_purgeDoc(C4Database* database, string docID, C4Error* outError) => Native.c4db_purgeDoc(database, docID, outError);
        public bool c4doc_setExpiration(C4Database* db, string docId, long timestamp, C4Error* outError) => Native.c4doc_setExpiration(db, docId, timestamp, outError);
        public long c4doc_getExpiration(C4Database* db, string docId) => Native.c4doc_getExpiration(db, docId);
        public C4Document* c4doc_put(C4Database *database, C4DocPutRequest *request, ulong* outCommonAncestorIndex, C4Error *outError) => Native.c4doc_put(database, request, outCommonAncestorIndex, outError);
        public C4Document* c4doc_create(C4Database* db, string docID, byte[] body, C4RevisionFlags revisionFlags, C4Error* error) => Native.c4doc_create(db, docID, body, revisionFlags, error);
        public C4Document* c4doc_update(C4Document* doc, byte[] revisionBody, C4RevisionFlags revisionFlags, C4Error* error) => Native.c4doc_update(doc, revisionBody, revisionFlags, error);
        public C4DatabaseObserver* c4dbobs_create(C4Database* database, C4DatabaseObserverCallback callback, void* context) => Native.c4dbobs_create(database, callback, context);
        public uint c4dbobs_getChanges(C4DatabaseObserver* observer, C4DatabaseChange[] outChanges, uint maxChanges, bool* outExternal) => Native.c4dbobs_getChanges(observer, outChanges, maxChanges, outExternal);
        public void c4dbobs_releaseChanges(C4DatabaseChange[] changes, uint numChanges) => Native.c4dbobs_releaseChanges(changes, numChanges);
        public void c4dbobs_free(C4DatabaseObserver* observer) => Native.c4dbobs_free(observer);
        public C4DocumentObserver* c4docobs_create(C4Database* database, string docID, C4DocumentObserverCallback callback, void* context) => Native.c4docobs_create(database, docID, callback, context);
        public void c4docobs_free(C4DocumentObserver* observer) => Native.c4docobs_free(observer);
        public void c4pred_registerModel(string name, C4PredictiveModel x) => Native.c4pred_registerModel(name, x);
        public bool c4pred_unregisterModel(string name) => Native.c4pred_unregisterModel(name);
        public C4Query* c4query_new(C4Database* database, string expression, C4Error* error) => Native.c4query_new(database, expression, error);
        public void c4query_free(C4Query* query) => Native.c4query_free(query);
        public string c4query_explain(C4Query* query) => Native.c4query_explain(query);
        public uint c4query_columnCount(C4Query* query) => Native.c4query_columnCount(query);
        public FLSlice c4query_columnTitle(C4Query* query, uint column) => Native.c4query_columnTitle(query, column);
        public C4QueryEnumerator* c4query_run(C4Query* query, C4QueryOptions* options, string encodedParameters, C4Error* outError) => Native.c4query_run(query, options, encodedParameters, outError);
        public bool c4queryenum_next(C4QueryEnumerator* e, C4Error* outError) => Native.c4queryenum_next(e, outError);
        public bool c4queryenum_seek(C4QueryEnumerator* e, ulong rowIndex, C4Error* outError) => Native.c4queryenum_seek(e, rowIndex, outError);
        public C4QueryEnumerator* c4queryenum_refresh(C4QueryEnumerator* e, C4Error* outError) => Native.c4queryenum_refresh(e, outError);
        public void c4queryenum_close(C4QueryEnumerator* e) => Native.c4queryenum_close(e);
        public void c4queryenum_free(C4QueryEnumerator* e) => Native.c4queryenum_free(e);
        public bool c4db_createIndex(C4Database* database, string name, string expressionsJSON, C4IndexType indexType, C4IndexOptions* indexOptions, C4Error* outError) => Native.c4db_createIndex(database, name, expressionsJSON, indexType, indexOptions, outError);
        public bool c4db_deleteIndex(C4Database* database, string name, C4Error* outError) => Native.c4db_deleteIndex(database, name, outError);
        public byte[] c4db_getIndexes(C4Database* database, C4Error* outError) => Native.c4db_getIndexes(database, outError);
        public C4Replicator* c4repl_new(C4Database* db, C4Address remoteAddress, FLSlice remoteDatabaseName, C4Database* otherLocalDB, C4ReplicatorParameters @params, C4Error* outError) => Native.c4repl_new(db, remoteAddress, remoteDatabaseName, otherLocalDB, @params, outError);
        public C4Replicator* c4repl_newWithSocket(C4Database* db, C4Socket* openSocket, C4ReplicatorParameters @params, C4Error* outError) => Native.c4repl_newWithSocket(db, openSocket, @params, outError);
        public void c4repl_free(C4Replicator* repl) => Native.c4repl_free(repl);
        public void c4repl_stop(C4Replicator* repl) => Native.c4repl_stop(repl);
        public C4ReplicatorStatus c4repl_getStatus(C4Replicator* repl) => Native.c4repl_getStatus(repl);
        public void c4socket_registerFactory(C4SocketFactory factory) => Native.c4socket_registerFactory(factory);
        public void c4socket_gotHTTPResponse(C4Socket* socket, int httpStatus, FLSlice responseHeadersFleece) => Native.c4socket_gotHTTPResponse(socket, httpStatus, responseHeadersFleece);
        public void c4socket_opened(C4Socket* socket) => Native.c4socket_opened(socket);
        public void c4socket_closed(C4Socket* socket, C4Error errorIfAny) => Native.c4socket_closed(socket, errorIfAny);
        public void c4socket_closeRequested(C4Socket* socket, int status, string message) => Native.c4socket_closeRequested(socket, status, message);
        public void c4socket_completedWrite(C4Socket* socket, ulong byteCount) => Native.c4socket_completedWrite(socket, byteCount);
        public void c4socket_received(C4Socket* socket, byte[] data) => Native.c4socket_received(socket, data);
        public C4Socket* c4socket_fromNative(C4SocketFactory factory, void* nativeHandle, C4Address* address) => Native.c4socket_fromNative(factory, nativeHandle, address);
        public FLDoc* FLDoc_FromResultData(FLSliceResult data, FLTrust x, FLSharedKeys* shared, FLSlice externData) => Native.FLDoc_FromResultData(data, x, shared, externData);
        public void FLDoc_Release(FLDoc* x) => Native.FLDoc_Release(x);
        public FLValue* FLDoc_GetRoot(FLDoc* x) => Native.FLDoc_GetRoot(x);
        public FLSharedKeys* FLDoc_GetSharedKeys(FLDoc* x) => Native.FLDoc_GetSharedKeys(x);
        public FLDoc* FLValue_FindDoc(FLValue* value) => Native.FLValue_FindDoc(value);
        public FLValue* FLValue_FromData(byte[] data, FLTrust x) => Native.FLValue_FromData(data, x);
        public byte[] FLData_ConvertJSON(byte[] json, FLError* outError) => Native.FLData_ConvertJSON(json, outError);
        public string FLValue_ToJSON(FLValue* value) => Native.FLValue_ToJSON(value);
        public string FLValue_ToJSONX(FLValue* v, bool json5, bool canonicalForm) => Native.FLValue_ToJSONX(v, json5, canonicalForm);
        public string FLJSON5_ToJSON(string json5, FLError* error) => Native.FLJSON5_ToJSON(json5, error);
        public FLValueType FLValue_GetType(FLValue* value) => Native.FLValue_GetType(value);
        public bool FLValue_IsInteger(FLValue* value) => Native.FLValue_IsInteger(value);
        public bool FLValue_IsUnsigned(FLValue* value) => Native.FLValue_IsUnsigned(value);
        public bool FLValue_IsDouble(FLValue* value) => Native.FLValue_IsDouble(value);
        public bool FLValue_AsBool(FLValue* value) => Native.FLValue_AsBool(value);
        public long FLValue_AsInt(FLValue* value) => Native.FLValue_AsInt(value);
        public ulong FLValue_AsUnsigned(FLValue* value) => Native.FLValue_AsUnsigned(value);
        public float FLValue_AsFloat(FLValue* value) => Native.FLValue_AsFloat(value);
        public double FLValue_AsDouble(FLValue* value) => Native.FLValue_AsDouble(value);
        public string FLValue_AsString(FLValue* value) => Native.FLValue_AsString(value);
        public byte[] FLValue_AsData(FLValue* value) => Native.FLValue_AsData(value);
        public FLArray* FLValue_AsArray(FLValue* value) => Native.FLValue_AsArray(value);
        public FLDict* FLValue_AsDict(FLValue* value) => Native.FLValue_AsDict(value);
        public string FLValue_ToString(FLValue* value) => Native.FLValue_ToString(value);
        public uint FLArray_Count(FLArray* array) => Native.FLArray_Count(array);
        public FLValue* FLArray_Get(FLArray* array, uint index) => Native.FLArray_Get(array, index);
        public void FLArrayIterator_Begin(FLArray* array, FLArrayIterator* i) => Native.FLArrayIterator_Begin(array, i);
        public FLValue* FLArrayIterator_GetValue(FLArrayIterator* i) => Native.FLArrayIterator_GetValue(i);
        public FLValue* FLArrayIterator_GetValueAt(FLArrayIterator* i, uint offset) => Native.FLArrayIterator_GetValueAt(i, offset);
        public uint FLArrayIterator_GetCount(FLArrayIterator* i) => Native.FLArrayIterator_GetCount(i);
        public bool FLArrayIterator_Next(FLArrayIterator* i) => Native.FLArrayIterator_Next(i);
        public uint FLDict_Count(FLDict* dict) => Native.FLDict_Count(dict);
        public FLValue* FLDict_Get(FLDict* dict, byte[] keyString) => Native.FLDict_Get(dict, keyString);
        public void FLDictIterator_Begin(FLDict* dict, FLDictIterator* i) => Native.FLDictIterator_Begin(dict, i);
        public FLValue* FLDictIterator_GetKey(FLDictIterator* i) => Native.FLDictIterator_GetKey(i);
        public string FLDictIterator_GetKeyString(FLDictIterator* i) => Native.FLDictIterator_GetKeyString(i);
        public FLValue* FLDictIterator_GetValue(FLDictIterator* i) => Native.FLDictIterator_GetValue(i);
        public bool FLDictIterator_Next(FLDictIterator* i) => Native.FLDictIterator_Next(i);
        public FLDictKey FLDictKey_Init(string str) => Native.FLDictKey_Init(str);
        public string FLDictKey_GetString(FLDictKey* dictKey) => Native.FLDictKey_GetString(dictKey);
        public FLValue* FLDict_GetWithKey(FLDict* dict, FLDictKey* dictKey) => Native.FLDict_GetWithKey(dict, dictKey);
        public FLEncoder* FLEncoder_New() => Native.FLEncoder_New();
        public void FLEncoder_Free(FLEncoder* encoder) => Native.FLEncoder_Free(encoder);
        public void FLEncoder_SetExtraInfo(FLEncoder* encoder, void* info) => Native.FLEncoder_SetExtraInfo(encoder, info);
        public void* FLEncoder_GetExtraInfo(FLEncoder* encoder) => Native.FLEncoder_GetExtraInfo(encoder);
        public void FLEncoder_Reset(FLEncoder* encoder) => Native.FLEncoder_Reset(encoder);
        public bool FLEncoder_WriteNull(FLEncoder* encoder) => Native.FLEncoder_WriteNull(encoder);
        public bool FLEncoder_WriteBool(FLEncoder* encoder, bool b) => Native.FLEncoder_WriteBool(encoder, b);
        public bool FLEncoder_WriteInt(FLEncoder* encoder, long l) => Native.FLEncoder_WriteInt(encoder, l);
        public bool FLEncoder_WriteUInt(FLEncoder* encoder, ulong u) => Native.FLEncoder_WriteUInt(encoder, u);
        public bool FLEncoder_WriteFloat(FLEncoder* encoder, float f) => Native.FLEncoder_WriteFloat(encoder, f);
        public bool FLEncoder_WriteDouble(FLEncoder* encoder, double d) => Native.FLEncoder_WriteDouble(encoder, d);
        public bool FLEncoder_WriteString(FLEncoder* encoder, string str) => Native.FLEncoder_WriteString(encoder, str);
        public bool FLEncoder_WriteData(FLEncoder* encoder, byte[] slice) => Native.FLEncoder_WriteData(encoder, slice);
        public bool FLEncoder_BeginArray(FLEncoder* encoder, ulong reserveCount) => Native.FLEncoder_BeginArray(encoder, reserveCount);
        public bool FLEncoder_EndArray(FLEncoder* encoder) => Native.FLEncoder_EndArray(encoder);
        public bool FLEncoder_BeginDict(FLEncoder* encoder, ulong reserveCount) => Native.FLEncoder_BeginDict(encoder, reserveCount);
        public bool FLEncoder_WriteKey(FLEncoder* encoder, string str) => Native.FLEncoder_WriteKey(encoder, str);
        public bool FLEncoder_EndDict(FLEncoder* encoder) => Native.FLEncoder_EndDict(encoder);
        public bool FLEncoder_WriteValue(FLEncoder* encoder, FLValue* value) => Native.FLEncoder_WriteValue(encoder, value);
        public FLDoc* FLEncoder_FinishDoc(FLEncoder* encoder, FLError* outError) => Native.FLEncoder_FinishDoc(encoder, outError);
        public byte[] FLEncoder_Finish(FLEncoder* e, FLError* outError) => Native.FLEncoder_Finish(e, outError);
        public bool FLSlice_Equal(FLSlice a, FLSlice b) => Native.FLSlice_Equal(a, b);
        public int FLSlice_Compare(FLSlice left, FLSlice right) => Native.FLSlice_Compare(left, right);
        public void FLSliceResult_Release(FLSliceResult slice) => Native.FLSliceResult_Release(slice);
        public FLSliceResult FLSlice_Copy(FLSlice slice) => Native.FLSlice_Copy(slice);
    }

    internal sealed unsafe class LiteCoreRawImpl : ILiteCoreRaw
    {
        public FLSliceResult c4error_getMessage(C4Error error) => NativeRaw.c4error_getMessage(error);
        public C4Error c4error_make(C4ErrorDomain domain, int code, FLSlice message) => NativeRaw.c4error_make(domain, code, message);
        public byte* c4log_getDomainName(C4LogDomain* x) => NativeRaw.c4log_getDomainName(x);
        public void c4slog(C4LogDomain* domain, C4LogLevel level, FLSlice msg) => NativeRaw.c4slog(domain, level, msg);
        public FLSliceResult c4_getVersion() => NativeRaw.c4_getVersion();
        public bool c4blob_keyFromString(FLSlice str, C4BlobKey* x) => NativeRaw.c4blob_keyFromString(str, x);
        public FLSliceResult c4blob_keyToString(C4BlobKey key) => NativeRaw.c4blob_keyToString(key);
        public C4BlobStore* c4blob_openStore(FLSlice dirPath, C4DatabaseFlags flags, C4EncryptionKey* encryptionKey, C4Error* outError) => NativeRaw.c4blob_openStore(dirPath, flags, encryptionKey, outError);
        public FLSliceResult c4blob_getContents(C4BlobStore* store, C4BlobKey key, C4Error* outError) => NativeRaw.c4blob_getContents(store, key, outError);
        public FLSliceResult c4blob_getFilePath(C4BlobStore* store, C4BlobKey key, C4Error* outError) => NativeRaw.c4blob_getFilePath(store, key, outError);
        public bool c4blob_create(C4BlobStore* store, FLSlice contents, C4BlobKey* expectedKey, C4BlobKey* outKey, C4Error* error) => NativeRaw.c4blob_create(store, contents, expectedKey, outKey, error);
        public UIntPtr c4stream_read(C4ReadStream* stream, byte[] buffer, UIntPtr maxBytesToRead, C4Error* outError) => NativeRaw.c4stream_read(stream, buffer, maxBytesToRead, outError);
        public bool c4stream_write(C4WriteStream* stream, byte[] bytes, UIntPtr length, C4Error* outError) => NativeRaw.c4stream_write(stream, bytes, length, outError);
        public C4Database* c4db_open(FLSlice path, C4DatabaseConfig* config, C4Error* outError) => NativeRaw.c4db_open(path, config, outError);
        public bool c4db_copy(FLSlice sourcePath, FLSlice destinationPath, C4DatabaseConfig* config, C4Error* error) => NativeRaw.c4db_copy(sourcePath, destinationPath, config, error);
        public bool c4db_deleteAtPath(FLSlice dbPath, C4Error* outError) => NativeRaw.c4db_deleteAtPath(dbPath, outError);
        public FLSliceResult c4db_getPath(C4Database* db) => NativeRaw.c4db_getPath(db);
        public C4RawDocument* c4raw_get(C4Database* database, FLSlice storeName, FLSlice docID, C4Error* outError) => NativeRaw.c4raw_get(database, storeName, docID, outError);
        public bool c4raw_put(C4Database* database, FLSlice storeName, FLSlice key, FLSlice meta, FLSlice body, C4Error* outError) => NativeRaw.c4raw_put(database, storeName, key, meta, body, outError);
        public bool c4doc_isOldMetaProperty(FLSlice prop) => NativeRaw.c4doc_isOldMetaProperty(prop);
        public FLSliceResult c4doc_getBlobData(FLDict* dict, C4BlobStore* blobStore, C4Error* outError) => NativeRaw.c4doc_getBlobData(dict, blobStore, outError);
        public FLSliceResult c4db_encodeJSON(C4Database* db, FLSlice jsonData, C4Error* outError) => NativeRaw.c4db_encodeJSON(db, jsonData, outError);
        public C4Document* c4doc_get(C4Database* database, FLSlice docID, bool mustExist, C4Error* outError) => NativeRaw.c4doc_get(database, docID, mustExist, outError);
        public bool c4doc_selectRevision(C4Document* doc, FLSlice revID, bool withBody, C4Error* outError) => NativeRaw.c4doc_selectRevision(doc, revID, withBody, outError);
        public bool c4doc_selectFirstPossibleAncestorOf(C4Document* doc, FLSlice revID) => NativeRaw.c4doc_selectFirstPossibleAncestorOf(doc, revID);
        public bool c4doc_selectNextPossibleAncestorOf(C4Document* doc, FLSlice revID) => NativeRaw.c4doc_selectNextPossibleAncestorOf(doc, revID);
        public bool c4doc_selectCommonAncestorRevision(C4Document* doc, FLSlice rev1ID, FLSlice rev2ID) => NativeRaw.c4doc_selectCommonAncestorRevision(doc, rev1ID, rev2ID);
        public uint c4rev_getGeneration(FLSlice revID) => NativeRaw.c4rev_getGeneration(revID);
        public int c4doc_purgeRevision(C4Document* doc, FLSlice revID, C4Error* outError) => NativeRaw.c4doc_purgeRevision(doc, revID, outError);
        public bool c4doc_resolveConflict(C4Document* doc, FLSlice winningRevID, FLSlice losingRevID, FLSlice mergedBody, C4RevisionFlags mergedFlags, C4Error* error) => NativeRaw.c4doc_resolveConflict(doc, winningRevID, losingRevID, mergedBody, mergedFlags, error);
        public bool c4db_purgeDoc(C4Database* database, FLSlice docID, C4Error* outError) => NativeRaw.c4db_purgeDoc(database, docID, outError);
        public bool c4doc_setExpiration(C4Database* db, FLSlice docId, long timestamp, C4Error* outError) => NativeRaw.c4doc_setExpiration(db, docId, timestamp, outError);
        public long c4doc_getExpiration(C4Database* db, FLSlice docId) => NativeRaw.c4doc_getExpiration(db, docId);
        public C4Document* c4doc_put(C4Database* database, C4DocPutRequest* request, UIntPtr* outCommonAncestorIndex, C4Error* outError) => NativeRaw.c4doc_put(database, request, outCommonAncestorIndex, outError);
        public C4Document* c4doc_create(C4Database* db, FLSlice docID, FLSlice body, C4RevisionFlags revisionFlags, C4Error* error) => NativeRaw.c4doc_create(db, docID, body, revisionFlags, error);
        public C4Document* c4doc_update(C4Document* doc, FLSlice revisionBody, C4RevisionFlags revisionFlags, C4Error* error) => NativeRaw.c4doc_update(doc, revisionBody, revisionFlags, error);
        public C4DocumentObserver* c4docobs_create(C4Database* database, FLSlice docID, C4DocumentObserverCallback callback, void* context) => NativeRaw.c4docobs_create(database, docID, callback, context);
        public C4Query* c4query_new(C4Database* database, FLSlice expression, C4Error* error) => NativeRaw.c4query_new(database, expression, error);
        public FLSliceResult c4query_explain(C4Query* query) => NativeRaw.c4query_explain(query);
        public C4QueryEnumerator* c4query_run(C4Query* query, C4QueryOptions* options, FLSlice encodedParameters, C4Error* outError) => NativeRaw.c4query_run(query, options, encodedParameters, outError);
        public bool c4db_createIndex(C4Database* database, FLSlice name, FLSlice expressionsJSON, C4IndexType indexType, C4IndexOptions* indexOptions, C4Error* outError) => NativeRaw.c4db_createIndex(database, name, expressionsJSON, indexType, indexOptions, outError);
        public bool c4db_deleteIndex(C4Database* database, FLSlice name, C4Error* outError) => NativeRaw.c4db_deleteIndex(database, name, outError);
        public FLSliceResult c4db_getIndexes(C4Database* database, C4Error* outError) => NativeRaw.c4db_getIndexes(database, outError);
        public void c4socket_closeRequested(C4Socket* socket, int status, FLSlice message) => NativeRaw.c4socket_closeRequested(socket, status, message);
        public void c4socket_completedWrite(C4Socket* socket, UIntPtr byteCount) => NativeRaw.c4socket_completedWrite(socket, byteCount);
        public void c4socket_received(C4Socket* socket, FLSlice data) => NativeRaw.c4socket_received(socket, data);
        public FLValue* FLValue_FromData(FLSlice data, FLTrust x) => NativeRaw.FLValue_FromData(data, x);
        public FLSliceResult FLData_ConvertJSON(FLSlice json, FLError* outError) => NativeRaw.FLData_ConvertJSON(json, outError);
        public FLSliceResult FLValue_ToJSON(FLValue* value) => NativeRaw.FLValue_ToJSON(value);
        public FLSliceResult FLValue_ToJSONX(FLValue* v, bool json5, bool canonicalForm) => NativeRaw.FLValue_ToJSONX(v, json5, canonicalForm);
        public FLSliceResult FLJSON5_ToJSON(FLSlice json5, FLError* error) => NativeRaw.FLJSON5_ToJSON(json5, error);
        public FLSlice FLValue_AsString(FLValue* value) => NativeRaw.FLValue_AsString(value);
        public FLSlice FLValue_AsData(FLValue* value) => NativeRaw.FLValue_AsData(value);
        public FLSliceResult FLValue_ToString(FLValue* value) => NativeRaw.FLValue_ToString(value);
        public FLValue* FLDict_Get(FLDict* dict, FLSlice keyString) => NativeRaw.FLDict_Get(dict, keyString);
        public FLSlice FLDictIterator_GetKeyString(FLDictIterator* i) => NativeRaw.FLDictIterator_GetKeyString(i);
        public FLDictKey FLDictKey_Init(FLSlice @string) => NativeRaw.FLDictKey_Init(@string);
        public FLSlice FLDictKey_GetString(FLDictKey* dictKey) => NativeRaw.FLDictKey_GetString(dictKey);
        public bool FLEncoder_WriteString(FLEncoder* encoder, FLSlice str) => NativeRaw.FLEncoder_WriteString(encoder, str);
        public bool FLEncoder_WriteData(FLEncoder* encoder, FLSlice slice) => NativeRaw.FLEncoder_WriteData(encoder, slice);
        public bool FLEncoder_BeginArray(FLEncoder* encoder, UIntPtr reserveCount) => NativeRaw.FLEncoder_BeginArray(encoder, reserveCount);
        public bool FLEncoder_BeginDict(FLEncoder* encoder, UIntPtr reserveCount) => NativeRaw.FLEncoder_BeginDict(encoder, reserveCount);
        public bool FLEncoder_WriteKey(FLEncoder* encoder, FLSlice str) => NativeRaw.FLEncoder_WriteKey(encoder, str);
        public FLSliceResult FLEncoder_Finish(FLEncoder* e, FLError* outError) => NativeRaw.FLEncoder_Finish(e, outError);
    }
}
