# This continuous integration pipeline is triggered anytime a user pushes code to the repo.
# This pipeline builds the .Net Core MacOS, Xamarin iOS, Xamarin Android projects, runs unit tests.
name: CBL NetCore MacOS, Xamarin iOS, Xamarin Android PR Validation

# Trigger on every master branch push and pull request
on:
  push:
    branches:
      - master
      - 'release/*'
  pull_request:
    branches:
      - '**'
    
jobs:

  build:

    strategy:
      fail-fast: false
      matrix:
        #[ubuntu-latest, windows-latest, macos-latest]
        os: [ macOS-latest ]
        #[x86, x64] Let's do x64 only
        targetplatform: [x64]
        
        dotnet-version: ['3.1.x']

    runs-on: ${{ matrix.os }}
    
    env:
      NEXUS_REPO: http://nexus.build.couchbase.com:8081/nexus/content/repositories/releases/com/couchbase/litecore
      KEYCHAIN_PWD: credentials("mobile-mac-mini-keychain")
    
    steps: 
    
    #Checkout CBL Net EE
    - name: Checkout CBL Net EE ${{ matrix.dotnet-version }}
      uses: actions/checkout@v2
      with:
        repository: couchbaselabs/couchbase-lite-net-ee
        token: ${{ secrets.GITHUBACTIONS_AT }}
        path: ./
        
    #Checkout CBL Net
    - name: Checkout ${{ matrix.dotnet-version }}
      uses: actions/checkout@v2
      with:
        path: ./couchbase-lite-net
        
    #Checkout CBL Net Validation solution
    - name: Checkout ${{ matrix.dotnet-version }}
      uses: actions/checkout@v2
      with:
        repository: couchbaselabs/couchbase-lite-net-validation
        path: ./jenkins/proj 
        
    #Run .Net Core MacOS tests
    - name: Run .Net Core ${{ matrix.dotnet-version }} MacOS tests
      working-directory: ${{github.workspace}}/jenkins
      shell: bash
      run: run_unix_tests.sh
    
    
