on:
  pull_request:
    branches: ["release/**"]
    paths-ignore:
      - "core_version.ini" # Ignore changes here since the relevant changes will have been approved in Core already.

jobs:
  warn-release:
    uses: couchbase/couchbase-lite-core/.github/workflows/warn_release.yml@master
    permissions:
      pull-requests: write
